name: Laravel

on:
  push:
    branches: [ "rodando-testes" ]
  pull_request:
    branches: [ "rodando-testes" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Entry directory project tests
      run: cd todoapp-api
    - name: Copy .env
      run: cd todoapp-api && php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: cd todoapp-api && ls && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: cd todoapp-api && php artisan key:generate
    - name: Directory Permissions
      run: cd todoapp-api && chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        cd todoapp-api && mkdir -p database
        touch database/database.sqlite
    - name: Execute migrations
      env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
      run: cd todoapp-api && php artisan migrate
    - name: Execute tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: cd todoapp-api && php artisan test
